#################################
# TOMCAT
#################################
server:
   port: 8088
   tomcat:
      threads:
         max: 10
         min-spare: 2
            
#server.error.path=
#server.servlet.session.timeout=

#################################
# DBCP
#################################
spring:
   main:
      allow-bean-definition-overriding: "true"
   
   datasource:
      hikari:
         driver-class-name: "org.postgresql.Driver"
         jdbc-url: "jdbc:postgresql://192.168.0.119:5432/cmmdb0_dev00?currentSchema=com_api&serverTimezone=Asia/Seoul"
         #jdbc-url: "jdbc:postgresql://125.6.40.234:5432/cmmdb0_dev00?currentSchema=com_api&serverTimezone=Asia/Seoul"
         username: "thenet"
         password: "thenet1!"

         auto-commit: false
         maximum-pool-size: 10
         connectionTimeout: 30000
         idleTimeout: 600000
         maxLifetime: 1800000
         connection-test-query: "SELECT 1"

#################################
# LOGGING
#################################
logging:
   pattern:
      #default log pattern
      #console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
      #custom log pattern
      console: '%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%4line]){magenta} %clr(%-40.40logger{39}){cyan} %clr(:){red} %m%n%wEx'
   level:
      root: info
      aicluster: info
      jdbc:
         resultset: error
         audit: error
      
#################################
# 환경설정
#################################
env:
   cors:
      origins:
         - "http://pc.atops.or.kr:8081"
         - "http://pc.atops.or.kr:8082"
         - "http://pc.atops.or.kr:8083"
         - "http://pc.atops.or.kr:8084"
         - "http://pc.atops.or.kr:8085"
         - "http://pc.atops.or.kr:8086"
         - "http://pc.atops.or.kr:8087"
         - "http://pc.atops.or.kr:8088"
         - "http://pc.atops.or.kr:5500"
      headers:
         - "Content-Disposition"
         - "Content-Language"
         - "Content-Transfer-Encoding"
         - "Content-Type"
      methods:
         - "*"
      pattern: "/**"
   cookie: 
      domain: "atops.or.kr"
      max-age: 1800
      secure: false
      httpOnly: true
      path: "/"
   dir:
      core-log: "C:/aica/logs/core-logs"
      upload: "C:/aica/upload"

