#################################
# TOMCAT
#################################
server:
   port: 8081
   tomcat:
      threads:
         max: 10
         min-spare: 2
            
#server.error.path=
#server.servlet.session.timeout=

#################################
# DBCP
#################################
spring:
   main:
      allow-bean-definition-overriding: "true"
   
   datasource:
      hikari:
         driver-class-name: "org.postgresql.Driver"
         jdbc-url: "jdbc:postgresql://fw.thenet-global.com:5432/thenetdb?currentSchema=new_public&serverTimezone=Asia/Seoul"
         username: "thenet"
         password: "thenet1!"

         auto-commit: false
         maximum-pool-size: 10
         connectionTimeout: 30000
         idleTimeout: 600000
         maxLifetime: 1800000
         connection-test-query: "SELECT 1"

#################################
# LOGGING
#################################
logging:
   pattern:
      rolling-file-name: "/home/dev-nps/app_test/logs/app/API_COMMON/app.%d{yyyy-MM-dd}.%i"
   file:
      name: "/home/dev-nps/app_test/logs/app/API_COMMON/app.log"
      max-history: 30
   level:
      root: info
      aicluster: debug
      jdbc:
         resultset: error
         audit: error
      
#################################
# 환경설정
#################################
env:
   cors:
      origins:
         - "http://pc.bnet.com:8081"
         - "http://pc.bnet.com:8082"
         - "http://pc.bnet.com:8083"
         - "http://pc.bnet.com:8084"
         - "http://pc.bnet.com:8085"
         - "http://pc.bnet.com:8086"
         - "http://pc.bnet.com:8087"
         - "http://pc.bnet.com:8088"
         - "http://pc.bnet.com:5500"
         - "http://api.bnet.com"
         - "http://ckment.com"
         - "http://125.6.37.87"
      headers:
         - "Content-Disposition"
         - "Content-Language"
         - "Content-Transfer-Encoding"
         - "Content-Type"
      methods:
         - "*"
      pattern: "/**"
   cookie: 
      domain: "bnet.com"
      #max-age = jwt.refreshTokenExpireTime / 1000 이어야 한다.
      max-age: 1800
      secure: false
      httpOnly: true
      path: "/"
   dir:
      core-log: "/home/dev-nps/app_test/logs"
      upload: "/home/dev-nps/app_test/uploads"

#################################
# 통합검색 환경설정
#################################
search:
    connection-timeout: 5000
    socket-timeout: 5000
    protocol: "http"
    domain: "172.22.2.25:7700"
    search-api-url: "/api/search.do"
    ark-api-url: "/api/ark.do"
    popword-api-url: "/api/popword.do"
    recommend-api-url: "/api/recommend.do"
    recommand-domain: "172.22.2.110:7700"
    recommand-list-api-url: "/api/recommandSearchList.do"
    recommand-dtl-api-url: "/api/recommandSearch.do"
    
      